---
title: Dart错误处理
date: 2024-9-27 10:22:24 +0800
categories:
  - dart
tags:
  - dart
  - flutter
description: Dart异常 throw ,try , catch ,finally ,on Exception , rethrow
math: true
---
> [Dart语言详解](https://rd-wang.github.io/posts/Dart基础概念和内部原理/)

## Exceptions
Dart 代码可以抛出和捕获异常。异常是指示发生意外情况的错误。如果未捕获异常，则引发异常的隔离(isolates)将被暂停，并且通常会终止隔离及其程序。
 
与 Java 不同，Dart 的所有异常都是未检查异常。方法不会声明它们可能抛出哪些异常，并且您不需要捕获任何异常。

Dart 提供`Exception`和`Error` 类型，以及许多预定义的子类型。当然，可以定义自己的异常。但是，Dart 程序可以将任何非空对象（不仅仅是 Exception 和 Error 对象）抛出为异常。

### Throw
以下是抛出或引发异常的示例：
```dart
throw FormatException('Expected at least 1 section');
```
你也可以throw任意对象
```dart
throw 'Out of llamas!';
```
> 生产质量代码通常会抛出实现错误或异常的类型。

因为抛出异常是一个表达式，所以你可以在 => 语句中以及允许表达式的任何其他地方抛出异常：

```dart
void distanceTo(Point other) => throw UnimplementedError();
```

### Catch
捕获异常会阻止异常传播（除非您重新抛出异常）。捕获异常使您有机会处理它：

```dart
try {
  breedMoreLlamas();
} on OutOfLlamasException {
  buyMoreLlamas();
}
```
要处理可能引发多种类型异常的代码，可以指定多个 catch 子句。与抛出对象类型匹配的第一个 catch 子句处理异常。如果 catch 子句未指定类型，则该子句可以处理任何类型的抛出对象：
```dart
try {
  breedMoreLlamas();
} on OutOfLlamasException {
  // A specific exception
  buyMoreLlamas();
} on Exception catch (e) {
  // Anything else that is an exception
  print('Unknown exception: $e');
} catch (e) {
  // No specified type, handles all
  print('Something really unknown: $e');
}
```

如上述代码所示，您可以使用 `on` 或 `catch` 或两者。当您需要指定异常类型时，请使用 `on`。当异常处理程序需要异常对象时，请使用 `catch`。

可以为 catch() 指定一个或两个参数。第一个是引发的异常，第二个是堆栈跟踪（StackTrace 对象）。
```dart
try {
  // ···
} on Exception catch (e) {
  print('Exception details:\n $e');
} catch (e, s) {
  print('Exception details:\n $e');
  print('Stack trace:\n $s');
}
```

要部分处理异常，同时允许其传播，请使用 `rethrow` 关键字。
```dart
void misbehave() {
  try {
    dynamic foo = true;
    print(foo++); // Runtime error
  } catch (e) {
    print('misbehave() partially handled ${e.runtimeType}.');
    rethrow; // Allow callers to see the exception.
  }
}

void main() {
  try {
    misbehave();
  } catch (e) {
    print('main() finished handling ${e.runtimeType}.');
  }
}
```

### Finally
为了确保无论是否引发异常，某些代码都会运行，请使用 finally 子句。如果没有 catch 子句与异常匹配，则在 finally 子句运行后传播异常：
```dart
try {
  breedMoreLlamas();
} finally {
  // Always clean up, even if an exception is thrown.
  cleanLlamaStalls();
}
```
finally 子句在任何匹配的 catch 子句之后运行：
```dart
try {
  breedMoreLlamas();
} catch (e) {
  print('Error: $e'); // Handle the exception first.
} finally {
  cleanLlamaStalls(); // Then clean up.
}
```

## Assert

在开发过程中，使用 assert 语句`assert(<condition>, <optionalMessage>);`——如果布尔条件为假，则中断正常执行。
```dart
// Make sure the variable has a non-null value.
assert(text != null);

// Make sure the value is less than 100.
assert(number < 100);

// Make sure this is an https URL.
assert(urlString.startsWith('https'));
```

要将消息附加到断言，请添加一个字符串作为第二个参数`assert` （可以选择在后面加上逗号）：
```dart
assert(urlString.startsWith('https'),
    'URL ($urlString) should start with "https".');
```
第一个参数`assert`可以是任何解析为布尔值的表达式。如果表达式的值为真，则断言成功并继续执行。如果为假，则断言失败并 `AssertionError`抛出异常（ ）。

断言到底什么时候起作用？这取决于你使用的工具和框架：
- Flutter 在调试模式下启用断言。
- 仅开发工具`webdev serve`通常默认启用断言。
- 一些工具，例如`dart run`和`dart compile js`通过命令行标志支持断言：`--enable-asserts`。

`assert`在生产代码中，断言被忽略，并且不会评估参数。